---
- name: install redhat dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - gcc
    - gcc-c++
    - automake
    - autoconf
    - make
    - git
    - wget
    - python-setuptools
    - libselinux-python
  when: ansible_os_family == "RedHat"

- name: install debian like dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - build-essential
    - python-setuptools
    - git 
    - wget 
  when: ansible_os_family == "Debian"

- name: install Arch Linux dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items: 
    - python2
    - python2-pip
    - git
    - libsodium
    - wget
  when: ansible_distribution == "Archlinux"

- name: install pip
  command: easy_install pip
  args:
    creates: /usr/bin/pip
  when: ansible_distribution != "Archlinux"

- name: install cymysql
  command: pip install cymysql
