---
- include: dependencies.yml
  tags:
    - install

- include: libsodium.yml
  when: ansible_os_family != "Archlinux"
  tags:
    - install

- include: server.yml
  tags:
    - config

- include: core.yml
  tags:
    - install

- include: config.yml
  tags: 
    - config

- include: fixes.yml
  tags:
    - fixes
